fix deal.II 9.2 instantiation bug in qprojector.h
Fixes #3728, which could generate the following error
```
In file included from /hdscratch/shared/libs-
candi-9.2.0-r1/deal.II-v9.2.0/include/deal.II/fe/mapping_cartesian.h:22:0,
                 from /home/heister/aspect-
git/source/simulator/core.cc:53,
                 from CMakeFiles/aspect.dir/Unity/unity_2_cxx.cxx:97:
/hdscratch/shared/libs-
candi-9.2.0-r1/deal.II-v9.2.0/include/deal.II/base/qprojector.h:414:54:
error: specialization of ‘dealii::QIterated<dim>::QIterated(const
dealii::Quadrature<1>&, unsigned int) [with int dim = 1]’ after
instantiation
                         const unsigned int   n_copies);
```

This is due to deal.II 9.2. having an incorrect specialization of
QIterated inside quadrature.h.