Fix FPE check with newer deal.II version
We forgot to set compiler flags (like c++11) when testing the floating
point exception stuff. You would get errors like:

/ssd/deal-build/installed/include/deal.II/base/exceptions.h:58:27:
error: expected ‘;’ at end of member declaration
/ssd/deal-build/installed/include/deal.II/base/exceptions.h:58:29:
error: ‘noexcept’ does not name a type