add instantiation of plugin list
Clang complains
```
./aspect/include/aspect/plugins.h:731:13: error: instantiation of
variable
'aspect::internal::Plugins::PluginList<aspect::BoundaryTemperature::Interface<3>>::plugins'
required here, but no definition is available
[-Werror,-Wundefined-var-template]
```